# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:18:19+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query
from pydantic import conint

from models import (
    Answered,
    AnsweringBodies,
    DailyReportViewModelSearchResult,
    HouseEnum,
    Members,
    ProblemDetails,
    QuestionStatusEnum,
    QuestionsViewModelItem,
    QuestionsViewModelSearchResult,
    StatementsViewModelItem,
    StatementsViewModelSearchResult,
)

app = MCPProxy(
    contact={
        'email': 'softwareengineering@parliament.uk',
        'name': 'UK Parliament',
        'url': 'https://www.parliament.uk/',
    },
    description='Data around written questions and answers, as well as written ministerial statements.',
    title='Written Questions Service API',
    version='v1',
)


@app.get('/api/dailyreports/dailyreports', tags=['daily_report_generation'])
def get_api_dailyreports_dailyreports(
    date_from: Optional[datetime] = Query(None, alias='dateFrom'),
    date_to: Optional[datetime] = Query(None, alias='dateTo'),
    house: Optional[HouseEnum] = None,
    skip: Optional[conint(ge=0, le=2147483647)] = None,
    take: Optional[conint(ge=0, le=2147483647)] = None,
):
    """
    Returns a list of daily reports
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/writtenquestions/questions', tags=['written_question_management'])
def get_api_writtenquestions_questions(
    asking_member_id: Optional[conint(ge=1, le=2147483647)] = Query(
        None, alias='askingMemberId'
    ),
    answering_member_id: Optional[conint(ge=1, le=2147483647)] = Query(
        None, alias='answeringMemberId'
    ),
    tabled_when_from: Optional[datetime] = Query(None, alias='tabledWhenFrom'),
    tabled_when_to: Optional[datetime] = Query(None, alias='tabledWhenTo'),
    answered: Optional[Answered] = None,
    answered_when_from: Optional[datetime] = Query(None, alias='answeredWhenFrom'),
    answered_when_to: Optional[datetime] = Query(None, alias='answeredWhenTo'),
    question_status: Optional[QuestionStatusEnum] = Query(None, alias='questionStatus'),
    include_withdrawn: Optional[bool] = Query(None, alias='includeWithdrawn'),
    expand_member: Optional[bool] = Query(None, alias='expandMember'),
    corrected_when_from: Optional[datetime] = Query(None, alias='correctedWhenFrom'),
    corrected_when_to: Optional[datetime] = Query(None, alias='correctedWhenTo'),
    search_term: Optional[str] = Query(None, alias='searchTerm'),
    u_i_n: Optional[str] = Query(None, alias='uIN'),
    answering_bodies: Optional[AnsweringBodies] = Query(None, alias='answeringBodies'),
    members: Optional[Members] = None,
    house: Optional[HouseEnum] = None,
    skip: Optional[conint(ge=0, le=2147483647)] = None,
    take: Optional[conint(ge=0, le=2147483647)] = None,
):
    """
    Returns a list of written questions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/writtenquestions/questions/{date}/{uin}', tags=['written_question_management']
)
def get_api_writtenquestions_questions__date__uin(
    date: datetime,
    uin: str = ...,
    expand_member: Optional[bool] = Query(None, alias='expandMember'),
):
    """
    Returns a written question
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/writtenquestions/questions/{id}', tags=['written_question_management'])
def get_api_writtenquestions_questions__id(
    id: int, expand_member: Optional[bool] = Query(None, alias='expandMember')
):
    """
    Returns a written question
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/writtenstatements/statements',
    tags=['written_statement_management', 'written_question_management'],
)
def get_api_writtenstatements_statements(
    made_when_from: Optional[datetime] = Query(None, alias='madeWhenFrom'),
    made_when_to: Optional[datetime] = Query(None, alias='madeWhenTo'),
    search_term: Optional[str] = Query(None, alias='searchTerm'),
    u_i_n: Optional[str] = Query(None, alias='uIN'),
    answering_bodies: Optional[AnsweringBodies] = Query(None, alias='answeringBodies'),
    members: Optional[Members] = None,
    house: Optional[HouseEnum] = None,
    skip: Optional[conint(ge=0, le=2147483647)] = None,
    take: Optional[conint(ge=0, le=2147483647)] = None,
    expand_member: Optional[bool] = Query(None, alias='expandMember'),
):
    """
    Returns a list of written statements
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/writtenstatements/statements/{date}/{uin}',
    tags=['written_statement_management'],
)
def get_api_writtenstatements_statements__date__uin(
    date: datetime,
    uin: str = ...,
    expand_member: Optional[bool] = Query(None, alias='expandMember'),
):
    """
    Returns a written statemnet
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/writtenstatements/statements/{id}', tags=['written_statement_management']
)
def get_api_writtenstatements_statements__id(
    id: int, expand_member: Optional[bool] = Query(None, alias='expandMember')
):
    """
    Returns a written statement
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
