# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:18:19+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any as Any_aliased
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Answered(Enum):
    Any = 'Any'
    Answered = 'Answered'
    Unanswered = 'Unanswered'


class AttachmentViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fileSizeBytes: Optional[int] = None
    fileType: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None


class GroupedQuestionViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dateTabled: Optional[datetime] = None
    questionUin: Optional[str] = None


class HouseEnum(Enum):
    Bicameral = 'Bicameral'
    Commons = 'Commons'
    Lords = 'Lords'


class Link(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    method: Optional[str] = None
    rel: Optional[str] = None


class MemberViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[int] = None
    listAs: Optional[str] = None
    memberFrom: Optional[str] = None
    name: Optional[str] = None
    party: Optional[str] = None
    partyAbbreviation: Optional[str] = None
    partyColour: Optional[str] = None
    thumbnailUrl: Optional[str] = None


class ProblemDetails(BaseModel):
    detail: Optional[str] = None
    instance: Optional[str] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class QuestionStatusEnum(Enum):
    NotAnswered = 'NotAnswered'
    AnsweredOnly = 'AnsweredOnly'
    AllQuestions = 'AllQuestions'


class QuestionsViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    answerIsCorrection: Optional[bool] = None
    answerIsHolding: Optional[bool] = None
    answerText: Optional[str] = None
    answeringBodyId: Optional[int] = None
    answeringBodyName: Optional[str] = None
    answeringMember: Optional[MemberViewModel] = None
    answeringMemberId: Optional[int] = None
    askingMember: Optional[MemberViewModel] = None
    askingMemberId: Optional[int] = None
    attachmentCount: Optional[int] = None
    attachments: Optional[List[AttachmentViewModel]] = None
    comparableAnswerText: Optional[str] = None
    correctingMember: Optional[MemberViewModel] = None
    correctingMemberId: Optional[int] = None
    dateAnswerCorrected: Optional[datetime] = None
    dateAnswered: Optional[datetime] = None
    dateForAnswer: Optional[datetime] = None
    dateHoldingAnswer: Optional[datetime] = None
    dateTabled: Optional[datetime] = None
    groupedQuestions: Optional[List[str]] = None
    groupedQuestionsDates: Optional[List[GroupedQuestionViewModel]] = None
    heading: Optional[str] = None
    house: Optional[HouseEnum] = None
    id: Optional[int] = None
    isNamedDay: Optional[bool] = None
    isWithdrawn: Optional[bool] = None
    memberHasInterest: Optional[bool] = None
    originalAnswerText: Optional[str] = None
    questionText: Optional[str] = None
    uin: Optional[str] = None


class QuestionsViewModelItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    links: Optional[List[Link]] = None
    value: Optional[QuestionsViewModel] = None


class QuestionsViewModelSearchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: Optional[List[QuestionsViewModelItem]] = None
    totalResults: Optional[int] = None


class StatementLinkTypeEnum(Enum):
    CorrectedStatement = 'CorrectedStatement'
    CorrectedAnswer = 'CorrectedAnswer'
    JointStatement = 'JointStatement'


class AnsweringBodies(RootModel[Optional[List[int]]]):
    root: Optional[List[int]] = Field(
        None,
        description='Written questions / statements relating to the answering bodies with the IDs specified',
    )


class Members(RootModel[Optional[List[int]]]):
    root: Optional[List[int]] = Field(
        None,
        description='Written questions / statements relating to the members with the IDs specified',
    )


class DailyReportViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: Optional[datetime] = None
    fileSizeBytes: Optional[int] = None
    house: Optional[HouseEnum] = None
    url: Optional[str] = None


class DailyReportViewModelItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    links: Optional[List[Link]] = None
    value: Optional[DailyReportViewModel] = None


class DailyReportViewModelSearchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: Optional[List[DailyReportViewModelItem]] = None
    totalResults: Optional[int] = None


class LinkedStatements(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    linkDate: Optional[datetime] = None
    linkType: Optional[StatementLinkTypeEnum] = None
    linkedStatementId: Optional[int] = None


class StatementsViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    answeringBodyId: Optional[int] = None
    answeringBodyName: Optional[str] = None
    attachments: Optional[List[AttachmentViewModel]] = None
    dateMade: Optional[datetime] = None
    hasAttachments: Optional[bool] = None
    hasLinkedStatements: Optional[bool] = None
    house: Optional[HouseEnum] = None
    id: Optional[int] = None
    linkedStatements: Optional[List[LinkedStatements]] = None
    member: Optional[MemberViewModel] = None
    memberId: Optional[int] = None
    memberRole: Optional[str] = None
    noticeNumber: Optional[int] = None
    text: Optional[str] = None
    title: Optional[str] = None
    uin: Optional[str] = None


class StatementsViewModelItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    links: Optional[List[Link]] = None
    value: Optional[StatementsViewModel] = None


class StatementsViewModelSearchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: Optional[List[StatementsViewModelItem]] = None
    totalResults: Optional[int] = None
